import { createStitches } from "@stitches/react";
import {
  gray,
  mauve,
  slate,
  sage,
  olive,
  sand,
  tomato,
  red,
  crimson,
  pink,
  plum,
  purple,
  violet,
  indigo,
  blue,
  cyan,
  teal,
  green,
  grass,
  orange,
  brown,
  bronze,
  gold,
  sky,
  mint,
  lime,
  yellow,
  amber,
  grayDark,
  blueDark,
  redDark,
  grassDark,
  sandDark,
  blackA,
  whiteA,
} from "@radix-ui/colors";

export const {
  styled,
  css,
  globalCss,
  keyframes,
  getCssText,
  theme,
  createTheme,
  config,
} = createStitches({
  theme: {
    colors: {
      ...gray,
      ...mauve,
      ...slate,
      ...sage,
      ...olive,
      ...sand,
      ...tomato,
      ...red,
      ...crimson,
      ...pink,
      ...plum,
      ...purple,
      ...violet,
      ...indigo,
      ...blue,
      ...cyan,
      ...teal,
      ...green,
      ...grass,
      ...orange,
      ...brown,
      ...bronze,
      ...gold,
      ...sky,
      ...mint,
      ...lime,
      ...yellow,
      ...amber,
      ...whiteA,
      overlay: "$colors$whiteA12",
    },
    media: {
      bp1: "(min-width: 480px)",
    },
    space: {
      1: "1rem",
      2: "2rem",
      3: "3rem",
    },
  },
});

export const darkTheme = createTheme({
  colors: {
    ...grayDark,
    ...blueDark,
    ...redDark,
    ...grassDark,
    ...sandDark,
    ...blackA,
    overlay: "$colors$blackA12",
  },
});

export const globalStyles = globalCss({
  "*": {
    margin: 0,
    padding: 0,
    boxSizing: "border-box",
  },
  html: { height: "100%" },
  body: {
    height: "100%",
    background: "$gray2",
    fontFamily: "Lato",
    lineHeight: "1.5",
    "-webkit-font-smoothing": "antialiased",
  },
  'div#__next': {
    height: '100%',
  },
  "h1,h2,h3,h4,h5,h6": {
    fontFamily: "Montserrat",
    letterSpacing: "2px",
  },
  button: {
    appearance: "none",
    background: "transparent",
    minWidth: "44px",
    minHeight: "44px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    color: "inherit",
  },
  "@font-face": [
    {
      fontFamily: "Montserrat",
      fontStyle: "regular",
      fontWeight: 400,
      fontDisplay: "swap",
      src: 'url("/fonts/Montserrat-Regular.ttf")',
    },
    {
      fontFamily: "Lato",
      fontStyle: "regular",
      fontWeight: 400,
      fontDisplay: "swap",
      src: 'url("/fonts/Lato-Regular.ttf")',
    },
    {
      fontFamily: "Lato",
      fontStyle: "medium",
      fontWeight: 600,
      fontDisplay: "swap",
      src: 'url("/fonts/Lato-SemiBold.ttf")',
    },
  ],
});
